name: checking github actions
on:
    push

jobs:
    github-action:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v2
        -   name: track changed files
            id: changed-files
            uses: tj-actions/changed-files@v41
            with:
                files: 'folder/**'
        -   name: step one
            id: step-one
            env:
                MOD_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
            run: |
                echo "DEBUG: step-one"
                declare -p MOD_FILES
                echo "FILES=$MOD_FILES" >> $GITHUB_OUTPUT
        -   name: step two
            id: step-two
            if: ${{ success() && steps.changed-files.outputs.all_changed_files != '' }}
            run: |
                echo "DEBUG: step-two"
                exit 0
        -   name: step three
            id: step-three
            env:
                STEP_ONE_CONCLUSION: ${{ steps.step-one.conclusion }}
                STEP_TWO_CONCLUSION: ${{ steps.step-two.conclusion }}
            if: ${{ success() }}
            run: |
                echo "DEBUG: step-three"
                echo "step-one:$STEP_ONE_CONCLUSION"
                echo "step-two:$STEP_TWO_CONCLUSION"
